isholiday/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.isChristmas, name = 'index'),
    path('time', views.time_day, name = 'time')
]

playground/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<str:name>', views.greeting, name ='greet')
]

task/urls.py
from django.urls import path
from . import views


app_name = 'task'
urlpatterns = [
    path('', views.task_view, name = 'task_view'),
    path('add', views.add_task, name = 'add_task')
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('task/', include( 'task.urls')),
    path('isholiday/', include('isholiday.urls')),
    path('playground/', include('playground.urls')),
    path('admin/', admin.site.urls),
]

task/models.py
from django.db import models

# Create your models here.

isholiday/views.py
from django.shortcuts import render
from datetime import datetime


# Create your views here.
def isChristmas (request):
    now = datetime.now()
    return render (request, 'isholiday/index.html', {
        'christmas' : now.month == 12 and now.year == 25
    })

def time_day (request):
    now = datetime.now()
    return render (request, 'isholiday/index.html', {
        'hour': now.hour, 'minute': now.minute
    })

playground/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index (request):
    return render (request, 'playground/index.html')

def greeting (request, name):
    return render (request, 'playground/index.html', {
        'name': name.capitalize()
    })

task/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse


class NewTaskForm (forms.Form):
        task = forms.CharField(
            label = 'New Activiy',
            widget=forms.TextInput(attrs={'placeholder': 'Add an activity'})
        )

# Create your views here.
def task_view (request):
    if 'tasklist' not in request.session:
        request.session['tasklist'] = []
    return render (request,'task/index.html',{
        'tasklist': request.session ['tasklist']
    } )

def add_task (request):
    # check if the methaod is a post (state altering)
    if request.method == 'POST':
        form = NewTaskForm(request.POST) # store user input in this class instancer
        #check the user input is the correct on the server side
        if form.is_valid():
            task = form.cleaned_data ['task'] #extracts validated and cleaned data from the input field task(in the class) into the variable
            request.session['tasklist'] += [task] #adds to list of activiities in the session
            return HttpResponseRedirect(reverse("task:task_view")) #takes the user back to the task list
        else:
            return render (request, 'task/add.html', {
                'form': form
            })

    return render (request, 'task/add.html', {
        'form': NewTaskForm()
    })

isholiday/templates/isholiday/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'isholiday/styles.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>What holiday is it ? </title>
</head>
<body>
    {% if christmas %}
    <h3>YES</h3>
    {% else %}
    <h3>NO</h3>
    {% endif %}
    <br/>
    <div>
        <p>{{ hour }} : {{ minute}}</p>
    </div>

</body>
</html>

playground/templates/playground/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Playground</title>
</head>
<body>
    <h1>Hello, {{ name }} !</h1>
</body>
</html>

task/templates/task/add.html
{% extends 'task/layout.html' %}

{% block body %}
 <form action="{% url 'task:add_task' %}" method="post">
        {% csrf_token%}
        {{form}}
        <input type="submit" value="Submit">
</form>

<a href="{% url 'task:task_view' %}">View to do list</a>
{% endblock %}

task/templates/task/index.html
{% extends 'task/layout.html' %}

{% block body %}
    <h3>Task list:</h3>
    <ul>
        {% for task in tasklist %}
            <li> {{ task }} </li>
        {% empty %} <!-- if the task is empty show below -->
            <li>No tasks.</li>
        {% endfor %}
    </ul>

<a href="{% url 'task:add_task' %}">Add activity</a>
{% endblock %}

task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Time to Work</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>